name: image-driven 
channels:
  - pytorch
  - nvidia
  - pyg 
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - torchvision=0.17.1
  - lightning=2.2.1
  - pytorch-scatter=2.1.2
  - numpy=1.26.4
  - matplotlib=3.8.3
  - imageio=2.34.0
  - sparse=0.15.1
  - mercantile=1.2.1
  - pandas=2.2.1
  - geopandas=0.14.3
  - pyproj=3.6.1
  - osmnx=1.9.3
  - ipykernel=6.29.3
  - pip:
    - calflops==0.3.2
    - einops==0.7.0
    - tensorboard==2.16.2
    - timm==1.0.7
    - thop==0.1.1-2209072238
